apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: SonarQube
    type: marcusolsson-json-datasource
    access: proxy
    url: http://sonarqube:9000
    editable: true
