server.port=8080
spring.application.name=devsecops-app

# Actuator - expose prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
